### ISSUE TITLE
Null Safety 

### ISSUE THREAD

**Issue by mustadev** [allansrc/time_elapsed#2]
when i try to use TimeElapsed i get this Error:

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:time_elapsed
2

For solutions, see https://dart.dev/go/unsound-null-safety

is there plans to add null safety to this package ?

thank you

**Comment by allansrc** [comment]
Hi!
I will work on that this weekend.
Next 07/09

I Will make u know when update this package, thx

**Comment by allansrc** [comment]
late but done

**Comment by mustadev** [comment]
better late than never :). thank you
